### ISSUE TITLE
Works with Ground Zeroes?

### ISSUE THREAD

**Issue by MavisCelus19201** [mi5hmash/MGSV_SaveTranslator#2]
Does this work with Ground Zeroes save format at all? (mgsv_gz_save_data_gl_en0), Just tried running it with that and opening it with NP++, it seemed to still be decrypted even after running it, but not sure if it decrypts that properly, though maybe I just don't know what to look out for there. Using a PC save for reference.

**Comment by mi5hmash** [comment]
Hi [MavisCelus19201](https://github.com/MavisCelus19201).
Regarding Ground Zeroes, it works partially. It does not allow the transfer of the SaveData files between gaming platforms (PC<>PS4) unlike the MGSVTP, because the file structure seems to be different on both platforms. The only gain it brings you here is the ability to change the region of your SaveData files on the same gaming platform. PS4 SaveData files have two layers of encryption (hardware and software). For hardware encryption, you can use [apollo-ps4 by bucanero](https://github.com/bucanero/apollo-ps4), but this requires the PS4 unit on firmware below or equal 9.00, to install and use the mentioned pkg. My tool can only decrypt the software layer.
What is your main objective?

**Comment by mi5hmash** [comment]
I am assuming this issue is solved because there was no response for 2 months.
